#Spring configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lt_db
    username: ltuser
    password: admin123
  jooq:
    sql-dialect: postgres

#Server Configuration
server:
  port: 8081

#Flyway Configuration
flyway:
  enabled: false



